
version: '3.9'


#docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-chrome:latest
services:
  chrome:
    image: selenium/standalone-chrome:4.10.0
    hostname: chrome
    privileged: true
    shm_size: 2gb
    ports:
      - "4441:4444"
      - "7901:7900"

  edge:
    image: selenium/standalone-edge:4.10.0
    hostname: edge
    privileged: true
    shm_size: 2gb
    ports:
      - "4442:4444"
      - "7902:7900"

  firefox:
    image: selenium/standalone-firefox:4.10.0
    hostname: firefox
    privileged: true
    shm_size: 2gb
    ports:
      - "4443:4444"
      - "7903:7900"



 # Despegar_Website_Chrome_Test:
 #   container_name: Despegar_Website_Chrome_Test_container
 #   build:
 #     context: .
 #     dockerfile: Dockerfile
 #   image: "despegar_website_chrome_test"
 #   depends_on:
 #     - chrome

