name: Purchase a flight ticket

on:
  push:
    branches:
      - main
        
jobs:

  run_purchase_flight_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Install Firefox
        uses: browser-actions/setup-firefox@v1
      - name: Test with Maven
        run: mvn clean test -Dsurefire.suiteXmlFiles="Testng.xml"
