# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Purchase a flight ticket

on:
  push:
    branches:
      - main


#jobs:
#  set_and_submit_flight_info:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Copy project into the virtual machine
#        uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'adopt' # See 'Supported distributions' for available options
#          java-version: '17'
#          cache: maven
#      - name: Build and run with Maven
#        run: mvn -B package --file pom.xml
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'
          cache: maven
      - name: Install Google Chrome
        run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  test_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Test with Maven
        run: mvn clean test
